FROM node:24-alpine AS build
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
ARG DEFAULT_PRIVATE_KEY_MIFOS
ARG DEMO_VITE_APP_USER_API_URL
ARG VITE_APP_BULK_PROCESSOR_URL
ARG VITE_APP_LOG_API_URL
ARG VITE_APP_THREAT_API_URL
ARG VITE_APP_USER_API_URL

ENV DEFAULT_PRIVATE_KEY_MIFOS=$DEFAULT_PRIVATE_KEY_MIFOS
ENV DEMO_VITE_APP_USER_API_URL=$DEMO_VITE_APP_USER_API_URL
ENV VITE_APP_BULK_PROCESSOR_URL=$VITE_APP_BULK_PROCESSOR_URL
ENV VITE_APP_LOG_API_URL=$VITE_APP_LOG_API_URL
ENV VITE_APP_THREAT_API_URL=$VITE_APP_THREAT_API_URL
ENV VITE_APP_USER_API_URL=$VITE_APP_USER_API_URL

RUN yarn build

FROM nginx:stable-alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
